### ISSUE TITLE
Erreur lors de la saisie du code du groupe

### ISSUE THREAD

**Issue by CuvelierMathieu** [eveoniris/larpManager-php#376]
En tant que joueur, je saisis le code de mon groupe et obtiens l'erreur suivante :

`Fatal error: Uncaught Error: Call to a member function getGroupe() on boolean in /home/eveoniri/larpmanager/src/LarpManager/Controllers/ParticipantController.php:1229 Stack trace: #0 /home/eveoniri/larpmanager/vendor/symfony/http-kernel/HttpKernel.php(135): LarpManager\Controllers\ParticipantController->groupeJoinAction(Object(Symfony\Component\HttpFoundation\Request), Object(Silex\Application), Object(LarpManager\Entities\Participant)) #1 /home/eveoniri/larpmanager/vendor/symfony/http-kernel/HttpKernel.php(57): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /home/eveoniri/larpmanager/vendor/silex/silex/src/Silex/Application.php(581): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /home/eveoniri/larpmanager/vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(89): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /home/eveoniri/larpmanager/vendor/symfony/htt in /home/eveoniri/larpmanager/src/LarpManager/Controllers/ParticipantController.php on line 1229`

L'url d'entrée : https://larpmanager.eveoniris.com/participant/7329/groupe/join
Si je saisis un code random, même erreur.

L'analyse du code indique que l'erreur est dans la méthode groupeJoinAction sur l'instruction

`$groupeGn = $app['orm.em']->getRepository('\LarpManager\Entities\GroupeGn')->findOneByCode($code);
$groupe = $groupeGn->getGroupe();`

J'en déduis que mon chef de groupe s'est viandé et ne m'a pas donné le bon code, mais il faudrait avoir un contrôle sur $groupeGn avant d'appeler son getGroupe().

PS : si vous avez besoin d'un coup de main de temps à autre pour le dev je peux être dispo.

**Comment by CuvelierMathieu** [comment]
My bad, doublon avec le #372 qui a déjà été géré.

**Comment by CuvelierMathieu** [comment]
En vrai pourquoi pas.
Si tu veux qu'on en cause sur Discord, mon pseudo c'est Gronork#4148
