### ISSUE TITLE
Incohérence sélection de personnage

### ISSUE THREAD

**Issue by Gectou4** [eveoniris/larpManager-php#435]
Sur une page Admin on constate que le joueur n'a pas de personnage de sélectionné.

Sur la page joueur on note que les joueurs on un personnage

Est-ce normal ? Quel comportement est attendus ici ?

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/1568376/230936619-4e6ff622-1488-4504-ada3-db53b2711510.png">

De plus sur la fiche l'etat civil du scenariste reste en balise TPL : 
<img width="461" alt="image" src="https://user-images.githubusercontent.com/1568376/230937092-3178a121-5678-419a-8f7b-04f1be39f90f.png">

Enfin:
```bash
Fatal error: Uncaught Error: Call to a member function getEtatCivil() on null in /usr/src/larpmanager/src/LarpManager/Entities/Personnage.php:1427 Stack trace: #0 /usr/src/larpmanager/cache/proxies/__CG__LarpManagerEntitiesPersonnage.php(937): LarpManager\Entities\Personnage->isSensible() #1 /usr/src/larpmanager/vendor/twig/twig/src/Template.php(700): DoctrineProxy\__CG__\LarpManager\Entities\Personnage->isSensible() #2 /usr/src/larpmanager/cache/twig/1b/1b552680ca7834ea71263eb6b16a9c29c5fcb6879a2ddcc69082a3419071c9b4.php(91): Twig\Template->getAttribute() #3 /usr/src/larpmanager/vendor/twig/twig/src/Template.php(453): __TwigTemplate_9d4c379bb6095cbec406eba07bbe0ff8c55d5d4b012e5f57fcf79e47cd6ed4da->doDisplay() #4 /usr/src/larpmanager/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling() #5 /usr/src/larpmanager/cache/twig/8e/8e5e91d0a43e65a2f172b3b62c313eebd49f69e815c4f8a27c518b22cd252c96.php(257): Twig\Template->display() #6 /usr/src/larpmanager/vendor/twig/twig/src/Template.php(214): __TwigTem in /usr/src/larpmanager/src/LarpManager/Entities/Personnage.php on line 1427
```

**Comment by ErenHistarion** [comment]
Corrigé pour la balise scénariste. :)

**Comment by Gectou4** [comment]
je vois cela, mais je t'ai fais une MR hier soir pour les 3 points de cette issue ;)
